version: '3.3'

services:

  eclipse-mosquitto:
    container_name: eclipse-mosquitto
    #image: eclipse-mosquitto
    image: ghcr.io/cobrafx/eclipse-mosquitto-cobra:v2
    #image: ghcr.io/cobrafx/domoticz-eclipse-mosquitto:v5
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/eclipse-mosquitto:/mosquitto/data
      - ./data/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./log:/mosquitto/log
    environment:
      - TZ=Europe/Kiev
    network_mode: "host"


  domoticz:
#    image: ghcr.io/cobrafx/domoticz-cobra:v5
#    image: domoticz/domoticz:stable
    image: ghcr.io/cobrafx/domoticz-cobra:v8
#    image: domoticz:v8
#    build:
#      context: .
#      dockerfile: Dockerfile 
    container_name: domoticz
    restart: unless-stopped
    tty: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
      #- /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0:/dev/ttyUSB0
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip1:/dev/gpiochip1
      - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A5069RR4-if00-port0:/dev/ttyRS485
    ports:
      - "8080:8080"
      - "443:443"
      - "9898:9898"
      - "4321:4321"
    volumes:
      - ./config:/opt/domoticz/userdata
      - ./backups:/opt/domoticz/backups
#      - ./backups:/opt/domoticz/userdata/backups
      - ./plugins/SVT:/opt/domoticz/plugins/SVT
      - ./plugins/zigbee2mqtt:/opt/domoticz/plugins/zigbee2mqtt
      - ./plugins/modbus-write:/opt/domoticz/plugins/modbus-write
      - ./plugins/modbus-read:/opt/domoticz/plugins/modbus-read
      - ./plugins/Domoticz-TinyTUYA-Plugin:/opt/domoticz/plugins/Domoticz-TinyTUYA-Plugin
      - ./plugins/Feyree-Charger:/opt/domoticz/plugins/Feyree-Charger
      - ./plugins/Powmr:/opt/domoticz/plugins/Powmr
      - ./plugins/Temperature-Garderobna:/opt/domoticz/plugins/Temperature-Garderobna
      - ./plugins/Temperature-Dah:/opt/domoticz/plugins/Temperature-Dah
      - ./plugins/Sun2000:/opt/domoticz/plugins/Sun2000
      - ./plugins/Tongou:/opt/domoticz/plugins/Tongou
      - ./plugins/BMS:/opt/domoticz/plugins/BMS
      - ./plugins/JK_BMS:/opt/domoticz/plugins/JK_BMS
      - ./data:/config
      - ./plugins/SVT:/opt/domoticz/plugins/userdata/SVT
      - ./plugins/zigbee2mqtt:/opt/domoticz/userdata/plugins/zigbee2mqtt
      - ./plugins/modbus-write:/opt/domoticz/userdata/plugins/modbus-write
      - ./plugins/modbus-read:/opt/domoticz/userdata/plugins/modbus-read
      - ./plugins/Domoticz-TinyTUYA-Plugin:/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin
      - ./plugins/Feyree-Charger:/opt/domoticz/userdata/plugins/Feyree-Charger
      - ./plugins/Powmr:/opt/domoticz/userdata/plugins/Powmr
      - ./plugins/Temperature-Garderobna:/opt/domoticz/userdata/plugins/Temperature-Garderobna
      - ./plugins/Temperature-Dah:/opt/domoticz/userdata/plugins/Temperature-Dah
      - ./plugins/Sun2000:/opt/domoticz/userdata/plugins/Sun2000
      - ./plugins/Tongou:/opt/domoticz/userdata/plugins/Tongou
      - ./plugins/BMS:/opt/domoticz/userdata/plugins/BMS
      - ./templates:/opt/domoticz/www/templates
      - /sys:/sys
      - ./scripts/dzVents:/opt/domoticz/scripts/dzVents
      - ./addons:/opt/addons
#    sysctls:
#      net.core.rmem_max: 262144
#      net.core.rmem_default: 262144
    environment:
      - TZ=Europe/Kiev
      - LOG_PATH=/opt/domoticz/userdata/domoticz.log
    network_mode: "host"
#    privileged: true

  zigbee2mqtt:
      container_name: zigbee2mqtt
      #image: ghcr.io/cobrafx/domoticz-zigbee2mqtt:v6
      #image: koenkk/zigbee2mqtt:1.38.0
      # image: koenkk/zigbee2mqtt:1.40.2
      #image: koenkk/zigbee2mqtt:1.42.0
      image: koenkk/zigbee2mqtt:2.1.3
      #image: koenkk/zigbee2mqtt:latest
      ports:
        - "8090:8090"
      volumes:
        - ./data:/app/data
        - /run/udev:/run/udev:ro
      devices:
        #- /dev/ttyACM0:/dev/ttyACM0
        # - /dev/ttyUSB1:/dev/ttyUSB1
        - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyCH341
        #- /dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00:/dev/ttyACM0
      restart: always
      environment:
        - TZ=Europe/Kiev
      network_mode: "host"
#      privileged: true



#  homeassistant:
#    container_name: homeassistant
#    image: "ghcr.io/home-assistant/home-assistant:stable"
#    volumes:
#      - ./homeassistant/config:/config
#      - /etc/localtime:/etc/localtime:ro
#      - /run/dbus:/run/dbus:ro
#    restart: unless-stopped
#    privileged: true
#    network_mode: host
